ALTER TABLE warehouse AUTO_INCREMENT = 0;
ALTER TABLE order_header AUTO_INCREMENT = 0;
ALTER TABLE order_line AUTO_INCREMENT = 0;
ALTER TABLE product AUTO_INCREMENT = 0;
ALTER TABLE warehouse_product AUTO_INCREMENT = 0;
ALTER TABLE shipment AUTO_INCREMENT = 0;